[package]
name = "text_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttf-parser = "0.19"
lrc = "0.1"
svg = "0.15"
